pull_requests:
  do_not_increment_build_number: true
skip_branch_with_pr: true
image: Visual Studio 2017
configuration: Release
shallow_clone: true
artifacts:
- path: TGS3-Server.zip
  name: TGS3Server
- path: MD5-SHA1-Server.txt
  name: MD5SHA1Server
- path: TGS3-Client.zip
  name: TGS3Client
- path: MD5-SHA1-Client.txt
  name: MD5SHA1Client
install:
  - choco install fciv
before_build:
  - nuget restore TGStationServer3.sln
build:
  project: TGStationServer3.sln
  parallel: true
  verbosity: minimal
after_build:
  - ps: .\TGS3Release.ps1
  - ps: if($env:APPVEYOR_REPO_COMMIT_MESSAGE -match "\[TGSDeploy\]"){$env:TGSDeploy = "Do it."}
  - ps: $env:TGSVersion = [System.Diagnostics.FileVersionInfo]::GetVersionInfo("$env:APPVEYOR_BUILD_FOLDER/TGServerService/bin/Release/TGServerService.exe").FileVersion
deploy:
  release: "tgstation-server-v$(TGSVersion)"
  description: 'The /tg/station server suite'
  provider: GitHub
  auth_token:
    secure: lJNGAXwiB5HlWdthz3K4PetqpTG5IEAyRgKaiKxFMQ8HW8CcOjRtB97B05op7BsK
  artifact: TGS3Server,MD5SHA1Server,TGS3Client,MD5SHA1Client
  draft: false
  prerelease: true
  on:
    TGSDeploy: "Do it."
