version: {build}
pull_requests:
  do_not_increment_build_number: true
environment:
  repo_token:
    secure: lJNGAXwiB5HlWdthz3K4PetqpTG5IEAyRgKaiKxFMQ8HW8CcOjRtB97B05op7BsK
branches:
  only:
    - master
    - V4
skip_tags: true
image: Visual Studio 2017
configuration:
  - Debug
  - Release
shallow_clone: true
artifacts:
  - path artifacts/ServerConsole
cache:
  - ~\.nuget\packages -> **\*.csproj
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
install:
  - choco install fciv doxygen.portable codecov
build:
  project: tgstation-server.sln
  parallel: false
  verbosity: minimal
  publish_nuget: true
after_build:
  - ps: Tools/PostCIBuild.ps1
  - ps: if($env:APPVEYOR_REPO_COMMIT_MESSAGE -match "\[TGSDeploy\]"){ if($env:APPVEYOR_REPO_BRANCH -match "master"){ $env:TGSDeploy = "Do it." }}
  - ps: if($env:APPVEYOR_REPO_COMMIT_MESSAGE -match "\[NugetDeploy\]"){ if($env:APPVEYOR_REPO_BRANCH -match "master"){ $env:NugetDeploy = "Do it." }}
  - ps: $env:TGSVersion = [System.Diagnostics.FileVersionInfo]::GetVersionInfo("$env:APPVEYOR_BUILD_FOLDER/TGS.Server/bin/Release/TGS.Server.dll").FileVersion
test_script:
  - set path=%ProgramFiles(x86)%\Microsoft Visual Studio\2017\TestAgent\Common7\IDE\CommonExtensions\Microsoft\TestWindow;%path%
  - copy "%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow\Extensions\appveyor.*" "%ProgramFiles(x86)%\Microsoft Visual Studio\2017\TestAgent\Common7\IDE\CommonExtensions\Microsoft\TestWindow\Extensions" /y
  - vstest.console /logger:trx;LogFileName=results.trx "src\Tgstation.Server.Host.Console.Tests\bin\Release\netcoreapp2.1\Tgstation.Server.Host.Console.Tests.dll" /Enablecodecoverage /Settings:"Tools/CoverageExclusions.runsettings" /inIsolation /Platform:x64
  - ps: $wc = New-Object 'System.Net.WebClient'
  - ps: $wc.UploadFile("https://ci.appveyor.com/api/testresults/mstest/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestResults\results.trx))
after_test:
  - ps: build/UploadCoverage.ps1
  - ps: build/BuildDox.ps1
  - ps: cd src/Tgstation.Server.Host.Console && dotnet publish -o artifacts/ServerConsole -c $env:CONFIGURATION
deploy:
  - provider: GitHub
    release: "tgstation-server-v$(TGSVersion)"
    description: 'The /tg/station server suite'
    auth_token:
      secure: lJNGAXwiB5HlWdthz3K4PetqpTG5IEAyRgKaiKxFMQ8HW8CcOjRtB97B05op7BsK
    artifact: TGS3Server,MD5SHA1Server,TGS3Client,MD5SHA1Client,TGS3ServerConsole,MD5SHA1ServerConsole
    draft: false
    on:
      TGSDeploy: "Do it."
  - provider: NuGet
    api_key:
      secure: bedsYuLMqGREzkVkJqRx+BTMgOvDO76tgaNc8sW5E3Ao6iw8oGHdJ/BZov8y0iKa
    skip_symbols: true
    artifact: /.*\.nupkg/
    on:
      NugetDeploy: "Do it."
