version: '{build}'
pull_requests:
  do_not_increment_build_number: true
environment:
  TGS4_TEST_DATABASE_TYPE: SqlServer
  TGS4_TEST_CONNECTION_STRING: Server=(local)\SQL2017;Initial Catalog=TGS_Test;User ID=sa;Password=Password12!
  TGS4_TEST_GITHUB_TOKEN:
    secure: lJNGAXwiB5HlWdthz3K4PetqpTG5IEAyRgKaiKxFMQ8HW8CcOjRtB97B05op7BsK
  TGS_RELEASE_NOTES_TOKEN:
    secure: lJNGAXwiB5HlWdthz3K4PetqpTG5IEAyRgKaiKxFMQ8HW8CcOjRtB97B05op7BsK
branches:
  only:
    - master
skip_tags: true
image: Visual Studio 2017
configuration:
  - Debug
  - Release
shallow_clone: true
artifacts:
  - path: artifacts/ServerConsole
    name: ServerConsole
  - path: artifacts/ServerService
    name: ServerService
  - path: artifacts/ServerHost
    name: ServerUpdatePackage
  - path: src/DMAPI
    name: DMAPI
cache:
  - ~\.nuget\packages -> **\*.csproj
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
services:
  - mssql2017
install:
  - choco install doxygen.portable codecov graphviz.portable opencover.portable
  - nuget restore tgstation-server.sln
build:
  project: tgstation-server.sln
  parallel: false
  verbosity: minimal
  publish_nuget: true
after_test:
  #host updater
  - dotnet publish src/Tgstation.Server.Host/Tgstation.Server.Host.csproj -o ../../artifacts/ServerHost -c %CONFIGURATION%
  #console
  - dotnet publish src/Tgstation.Server.Host.Console/Tgstation.Server.Host.Console.csproj -o ../../artifacts/ServerConsole -c %CONFIGURATION%
  - ps: Copy-Item -path "artifacts/ServerHost" -destination artifacts/ServerConsole/lib/Default -recurse
  - ps: Move-Item -path artifacts/ServerConsole/lib/Default/appsettings.json -destination artifacts/ServerConsole/
  #service
  - ps: Copy-Item -path "src/Tgstation.Server.Host.Service/bin/$env:CONFIGURATION" -destination artifacts/ServerService -recurse
  - ps: Copy-Item -path "artifacts/ServerHost" -destination artifacts/ServerService/lib/Default -recurse
  - ps: Move-Item -path artifacts/ServerService/lib/Default/appsettings.json -destination artifacts/ServerService/
  - ps: Remove-Item artifacts/ServerHost/appsettings.json
  #deploy stuff
  - ps: build/prep_deployment.ps1
  - ps: Write-Host $env:TGSReleaseNotes
  - ps: Write-Host $env:TGSGoodNotes
deploy:
  - provider: GitHub
    release: "tgstation-server-v$(TGSVersion)"
    description: "$(TGSReleaseNotes)"
    auth_token:
      secure: lJNGAXwiB5HlWdthz3K4PetqpTG5IEAyRgKaiKxFMQ8HW8CcOjRtB97B05op7BsK
    artifact: ServerConsole,ServerService,ServerUpdatePackage,DMAPI
    draft: $(TGSGoodNotes)
    prerelease: true
    on:
      TGSDeploy: "Do it."
  - provider: NuGet
    api_key:
      secure: EIZSw7MBSZ4mICMO09qoV5FjCT0XYz4lsMZ9U3ZTQIn7Ll/eUbQp4itCBtoy7B4M
    skip_symbols: true
    artifact: /.*\.nupkg/
    on:
      NugetDeploy: "Do it."
